### ISSUE TITLE
The specific commit as the starting point

### ISSUE THREAD

**Issue by hipertracker** [lukaszraczylo/semver-generator#1]
The application should be able to start the calculations from the (optionally) defined commit instead form the first one (default). This should help to calculate the proper SEM numbers for the legacy code.

Eg.
```yaml 
force:
  major: 7
  minor: 4
  patch: 5
  commit: 1c8e2eb628bc7c82f914b14b1163710be24ed510
```
