### ISSUE TITLE
'strict' and 'existing' flags not working from config file

### ISSUE THREAD

**Issue by martingleria** [lukaszraczylo/semver-generator#13]
Hi!

Let me spend one line making an explicit **thank you** for sharing your knowledge and time in this project. 

Now, to the issue:

I was testing your tool to incorporate it into our workflows. I found that the recently added `existing: true` flag, and also the _strict_ flag don't work from the config file. 

This is my config file:

```
version: 1
force:
  existing: true
  strict: true
wording:
  patch:
    - update
    - fix
  minor:
    - feature
    - improve
  major:
    - breaking
    - major
  release:
    - release-candidate
    - add-rc
```

I was originally testing directly from a Github Action:

```
name: Testing semver

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Preparing build context
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.semver.outputs.semantic_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Semver run
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: semver.yml
          repository_local: true
      - name: Semver check
        run: |
          echo "Semantic version detected: ${{ steps.semver.outputs.semantic_version }}"
```

The result was that existing tags were not taken into account, and strict mode didn't work either. 

I download the project to test it locally and I realized that from my local computer I'm able to reproduce the same behavior running the binary in this way (semver.yml is the same one I included before):

```
./semver-gen generate -l  -c semver.yml
SEMVER 0.0.13
```

But if I run explicitly including the flags the result is the desired one:

````
./semver-gen generate -l -s -e -c semver.yml
SEMVER 0.1.0
````

Am I doing something wrong? Otherwise, I hope this requires minimal effort on your side since it's all I need for my workflows right now. 

Thanks again.
