### ISSUE TITLE
strict: false flag seems to not work

### ISSUE THREAD

**Issue by joonasjarvinen92** [lukaszraczylo/semver-generator#20]
**Describe the bug**

Hi! I tried adding a `strict: false` flag to the pipeline but the PATCH version seems to not increment when there are no matching keywords.

**Output with debug**
[ paste output of the command with `-d` flag here ]

**Expected behavior**

If the strict flag is false, the PATCH number should increment without matching keywords.

**Additional context**

- Noticed the warning about the strict flag

![image](https://user-images.githubusercontent.com/95740220/228751257-c6a4e5de-bb60-4352-9693-0e2dd209e69e.png)

- Not sure if the `!params.varStrict` in code should be without negation?

```
if !params.varStrict && !s.Force.Strict {
	s.Semver.Patch++
	debugPrint(fmt.Sprintln("Incrementing patch (DEFAULT) on ", strings.TrimSuffix(commit.Message, "\n"), "| Semver:", s.getSemver()))
}
```

- did read this https://github.com/lukaszraczylo/semver-generator/issues/12#issuecomment-1486356946

**Comment by lukaszraczylo** [comment]
Could you try doing the same with the strict mode in yaml file?

For example
```
version: 1
force:
  major: 1
  existing: false
  strict: false
wording:
  patch:
    - update
    - initial
    - fix
  minor:
    - change
    - improve
  major:
    - breaking
  release:
    - release-candidate
```
