### ISSUE TITLE
Major version incremented for no new commit

### ISSUE THREAD

**Issue by hipertracker** [lukaszraczylo/semver-generator#5]
It increments a major number by 1  even when no new code commit was sent. 

E.g for config.yml

```yaml
version: 1
force:
  major: 1
  minor: 4
  patch: 12
  commit: 1c8e2eb628bc7c82f914b14b1163710be24ed510
wording:
  patch:
    - update
    - initial
  minor:
    - add
    - change
    - improve
  major:
    - breaking
    - the # For testing purposes
```

```
❯ semver-gen generate -c config.yml -r https://github.com/hipertracker/words_extractor
SEMVER 2.4.12
```

It should be 1.4.12
