### ISSUE TITLE
Github action does not seem to work

### ISSUE THREAD

**Issue by kcross-ctoken** [lukaszraczylo/semver-generator#50]
**Describe the bug**
The action fails with no output

**Output with debug**
none

**Expected behavior**
to at least put error output

**Additional context**
I would suggest using the github action in your own release scripts to check that it works for creating the release versions. I.e. dogfood your release in the release scripts instead of 
```
         DOWNLOAD_URL=$(curl -s https://api.github.com/repos/lukaszraczylo/semver-generator/releases/latest | grep -E ".*browser_download_url.*linux-" | grep -vE "(arm64|md5)" \
            | cut -d '"' -f 4)
          curl -s -L -o semver-gen "$DOWNLOAD_URL" && chmod +x semver-gen
          TMP_RELEASE_VERSION=$(./semver-gen generate -l -c config-release.yaml | sed -e 's|SEMVER ||g')
```
Since this is the only why it seems to work Im now having to use this instead of the github action.

**Comment by lukaszraczylo** [comment]
Thank you for reporting, having a look now.

**Comment by lukaszraczylo** [comment]
@kcross-ctoken how do you use the github action? I've re-ran it on one of the repositories:

https://github.com/lukaszraczylo/go-simple-graphql/actions/runs/10263942990/job/28396864774

```
      - name: Establish semver
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: semver.yaml
          repository_local: true
          github_username: ${{ github.ACTOR }}
          github_token: $GHCR_TOKEN

      - name: Semver check
        run: |
          echo "Semantic version detected: ${{ steps.semver.outputs.semantic_version }}"
```

You need to create semver.yaml file in the repository root, and it just works :)

**Comment by kcross-ctoken** [comment]
hmmm let me try again

**Comment by kcross-ctoken** [comment]
when I put the repository as    
`repository_url: ${{ github.server_url }}/${{ github.repository }}` it fails with no errors or outputs 
if I use repository_local: true it comes back with 0.0.0
If I use the command on the same repo locally `./semver-gen generate -l -c semver.yaml -e | sed -e 's|SEMVER ||g'  it comes back with `0.0.23`


Im using this atm:

```yaml
      - name: semver config
        uses: "DamianReeves/write-file-action@master"
        with:
          path: semver.yaml
          write-mode: overwrite
          contents: |
            version: 1
            wording:
              minor:
                - feat
              major:
                - breaking

      - name: Establish semver
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: semver.yaml
          repository_local: true
          #repository_url: ${{ github.server_url }}/${{ github.repository }}
          github_username: ${{ github.ACTOR }}
          github_token: ${{secrets.REPO_RO_TOKEN}}
          strict: false
          existing: true
```
