### ISSUE TITLE
Patch version being updated instead of minor

### ISSUE THREAD

**Issue by Wuerike** [lukaszraczylo/semver-generator#8]
During my tests when using the default config.yaml I noticed that minor keywords are acting as they were the patch ones.

It happened with **add** and **change** but **NOT** with **improve**.

config.yaml
```
version: 1
force:
  major: 1
  commit: 4dc131734b6e7504ebd185d70b5777059880ab59
wording:
  patch:
    - update
    - initial
    - fix
  minor:
    - add
    - change
    - improve
  major:
    - breaking
```

I got the following

```
Initially: 1.0.2
Breaking commit: 2.0.1
Change commit: 2.0.2
Update commit: 2.0.3
Improve commit: 2.1.1
Improve commit: 2.2.1
Add commit: 2.2.2
```
